### ISSUE TITLE
Catalina: endpointSecurityFactoryError

### ISSUE THREAD

**Issue by JayBrown** [trailofbits/sinter#95]
Sinter doesn't seem to work. I'm getting constant `Failed to create the AuthorizationManager object: endpointSecurityFactoryError` errors in `/var/log/sinter_stdout.log`.

macOS 10.15.5

**Comment by alessandrogario** [comment]
> Sinter doesn't seem to work. I'm getting constant `Failed to create the AuthorizationManager object: endpointSecurityFactoryError` errors in `/var/log/sinter_stdout.log`.
> 
> macOS 10.15.5

Hello @JayBrown,

thanks for the bug report! Would it be possible to include the output of the log file? By default, it should be located at the following path: `/var/log/sinter.log`

**Comment by JayBrown** [comment]
The only errors/infos in the log file (but constantly repeating), are:

```
{ "timestamp": "2020-Aug-25 23:03:41", "type": "message", "severity": "error", "message": "The EndpointSecurity factory returned an error: initializationError" }
{ "timestamp": "2020-Aug-25 23:03:51", "type": "message", "severity": "information", "message": "Initializing the local decision manager plugin" }
```

**Comment by alessandrogario** [comment]
Hello @JayBrown,

thanks for providing the log file! We have a PR up to [https://github.com/trailofbits/sinter/pull/97](improve logging) which should help us troubleshoot the problem more easily.

Is the binary from the packages we have released, or a custom-built one? If the binary was started from the terminal application, is it possible to verify that it has "Full Disk Access" permission is enabled?

**Comment by JayBrown** [comment]
It's not a custom build, but the release version. iTerm has FDA, but this also happens after a reboot, without me touching sinter via iTerm in any way. Will try out the new version.

**Comment by JayBrown** [comment]
So the new extended log shows the following:

```
{ "timestamp": "2020-Aug-27 12:41:48", "type": "message", "severity": "information", "message": "Initializing the local decision manager plugin" }
{ "timestamp": "2020-Aug-27 12:41:48", "type": "message", "severity": "error", "message": "The EndpointSecurity factory returned an error: The caller isn't permitted to connect to Endpoint Security" }
```

**Comment by alessandrogario** [comment]
Hello @JayBrown 

The error code returned is `ES_NEW_CLIENT_RESULT_ERR_NOT_PERMITTED` which in the Apple documentation reads as follows: `This error indicates the app lacks Transparency, Consent, and Control (TCC) approval from the user.`.

This seems to indicate the the Sinter.app application was not granted the Full Disk Access permission. Would it be possible to check the configuration so we can exclude this problem?

Thanks for your help in debugging this!

**Comment by JayBrown** [comment]
Oh, yes… Sinter was in my FDA list, but for a weird reason, it wasn't ticked.
